# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "client<llm> OllamaQwen32 {\n  provider \"openai-generic\"\n  options {\n    base_url env.BAML_OLLAMA_BASE_URL\n    model env.BAML_OLLAMA_MODEL\n    temperature 0.0\n    max_tokens 2048\n    timeout_ms 30000\n  }\n}\n",
    "extract_authors.baml": "function ExtractAuthorsFromHeader(header_text: string) -> AuthorExtractionResult {\n  client OllamaQwen32\n  prompt #\"\n    You extract author names from scientific paper header text.\n\n    Task:\n    - Return ONLY human author names.\n    - Keep original spelling when possible.\n    - Remove affiliations, institutes, universities, hospitals, addresses, section labels,\n      copyright text, dates, editorial notes, and publication metadata.\n    - Remove duplicates while preserving order.\n    - If unsure, return only clearly identifiable person names.\n\n    Input header text:\n    {{header_text}}\n\n    {{ ctx.output_format(prefix=\"Use the following OUTPUT FORMAT:\") }}\n  \"#\n}\n\nfunction ExtractTitleFromHeader(header_text: string) -> TitleExtractionResult {\n  client OllamaQwen32\n  prompt #\"\n    You extract the scientific paper title from header text.\n\n    Task:\n    - Return exactly one title string.\n    - Return only the paper title.\n    - Remove author names, affiliations, journal header/footer, copyright/license text,\n      DOI lines, section labels (e.g. ABSTRACT, INTRODUCTION), and page metadata.\n    - Preserve original title wording and punctuation where possible.\n\n    Input header text:\n    {{header_text}}\n\n    {{ ctx.output_format(prefix=\"Use the following OUTPUT FORMAT:\") }}\n  \"#\n}\n",
    "generators.baml": "generator target {\n  output_type \"python/pydantic\"\n  output_dir \"../\"\n  version \"0.222.0\"\n  default_client_mode sync\n}\n",
    "structures.baml": "class AuthorExtractionResult {\n  authors string[] @description(\"Cleaned person names only. No institutions, affiliations, editorial text, or section labels.\")\n}\n\nclass TitleExtractionResult {\n  title string @description(\"Cleaned paper title only. No author list, affiliations, journal metadata, copyright, or section labels.\")\n}\n",
}

def get_baml_files():
    return _file_map