# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (2)
# #########################################################################

class AuthorExtractionResult(BaseModel):
    authors: typing.List[str] = Field(description='Cleaned person names only. No institutions, affiliations, editorial text, or section labels.')

class TitleExtractionResult(BaseModel):
    title: typing.Optional[str] = Field(default=None, description='Cleaned paper title only. No author list, affiliations, journal metadata, copyright, or section labels.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
